export const CONFIG = {
  gravity: -38,
  airAcceleration: 13.5,
  walkSpeed: 9.4,
  groundAcceleration: 42,
  groundDeceleration: 46,
  groundProbeDistance: 1.34,
  maxAirSpeed: 71,
  ropeMaxRange: 115,
  ropeMinLength: 7,
  ropePullSpeed: 17,
  ropePullMaxSpeed: 36,
  ropeSpring: 58,
  ropeDamping: 8,
  ropeReelAcceleration: 7.2,
  ropeReelMaxAcceleration: 27,
  ropeReelRadialForce: 24,
  ropeReleaseBoost: 6.8,
  ropeReleaseLift: 2.55,
  hitscanRange: 145,
  bombTrackRange: 205,
  bombLockNdcRadius: 0.43,
  aimPerfectNdcRadius: 0.22,
  aimGrazeNdcRadius: 0.43,
  bombEngageRange: 105,
  bombApproachSpeed: 7.5,
  bombImpactDistance: 4.5,
  minimumBombs: 2,
  bombInitialSpawnDelay: 0.55,
  bombRespawnDelayMin: 1.8,
  bombRespawnDelayMax: 2.8,
  bombSpawnDistanceMin: 102,
  bombSpawnDistanceMax: 142,
  bombSpawnLateralMin: 22,
  bombSpawnLateralMax: 52,
  bombScale: 1.34,
  staminaGroundDrain: 32,
  staminaGroundIdleDrain: 12,
  staminaAirRecharge: 18,
  staminaGrappleRecharge: 30,
  dashMinimumStamina: 30,
  dashMinimumSpeed: 42,
  dashMaximumSpeed: 66,
  dashMinimumDuration: 0.24,
  dashMaximumDuration: 0.61,
  jumpBoostMinimumSpeed: 27,
  jumpBoostMaximumSpeed: 47,
  ropeFireDuration: 0.085,
  chunkSize: 128,
  chunkRadius: 2,
  pickupTargetCount: 34,
  pickupCollectionRadiusNormal: 8,
  pickupCollectionRadiusGold: 10,
  pickupNormalScore: 65,
  pickupGoldScore: 190,
  healthPackCount: 3,
  healthPackSpawnChance: 0.18,
  healthPackTrackRange: 175,
  healthPackHealGraze: 16,
  healthPackHealPerfect: 32,
  stageScoreBase: 12000,
  stageScoreGrowth: 6000,
  stageTransitionDuration: 3,
  playerBaseHealth: 100,
  combatTrackRange: 190,
  droneAimPerfectNdcRadius: 0.31,
  droneAimGrazeNdcRadius: 0.62,
  droneDetectionRange: 145,
  droneFireRange: 105,
  droneMoveSpeed: 10,
  droneBulletSpeed: 38,
  droneBulletDamage: 7,
} as const;

export type RunMode = 'ready' | 'playing' | 'paused' | 'upgrade' | 'over';
export type TargetKind = 'normal' | 'gold' | 'bomb' | 'health';

export interface RunStats {
  score: number;
  combo: number;
  bestCombo: number;
  shots: number;
  hits: number;
  topSpeed: number;
  falls: number;
}
